# Generated by Django 4.1.5 on 2023-03-13 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'نام کاریری', 'verbose_name_plural': 'نام های کاربری'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='Melicode',
            field=models.CharField(max_length=10, unique=True, verbose_name='کدملی '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fathers_name',
            field=models.CharField(max_length=40, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/profile', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
