# Generated by Django 4.1.5 on 2023-01-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_category_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='floatfield',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='article',
            name='myfile',
            field=models.FileField(blank=True, null=True, upload_to='test'),
        ),
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
